using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using PawsomePets.Permissions;
using PawsomePets.MediaStorages;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using PawsomePets.Shared;

namespace PawsomePets.MediaStorages
{
    public class MediaStoragesAppService : MediaStoragesAppServiceBase, IMediaStoragesAppService
    {
        //<suite-custom-code-autogenerated>
        public MediaStoragesAppService(IMediaStorageRepository mediaStorageRepository, MediaStorageManager mediaStorageManager, IDistributedCache<MediaStorageDownloadTokenCacheItem, string> downloadTokenCache)
            : base(mediaStorageRepository, mediaStorageManager, downloadTokenCache)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}