using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp.Domain.Entities;

using Volo.Abp;

namespace PawsomePets.DogPets
{
    public class DogPet : DogPetBase
    {
        //<suite-custom-code-autogenerated>
        protected DogPet()
        {

        }

        public DogPet(float age, float weight, int vaccinations, decimal price, float promotionPecents, bool isStock, string? name = null, string? breed = null, string? gender = null, string? color = null, string? healthStatus = null, string? otherInformation = null)
            : base(age, weight, vaccinations, price, promotionPecents, isStock, name, breed, gender, color, healthStatus, otherInformation)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}