using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace PawsomePets.DogPets
{
    public class DogPetManager : DogPetManagerBase
    {
        //<suite-custom-code-autogenerated>
        public DogPetManager(IDogPetRepository dogPetRepository)
            : base(dogPetRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}