using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace PawsomePets.MediaStorages
{
    public class MediaStorageManager : MediaStorageManagerBase
    {
        //<suite-custom-code-autogenerated>
        public MediaStorageManager(IMediaStorageRepository mediaStorageRepository)
            : base(mediaStorageRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}