using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp.Domain.Entities;

using Volo.Abp;

namespace PawsomePets.MediaStorages
{
    public class MediaStorage : MediaStorageBase
    {
        //<suite-custom-code-autogenerated>
        protected MediaStorage()
        {

        }

        public MediaStorage(bool isMain, string? imageName = null, string? imageUrl = null, string? description = null, string? fileType = null, float? fileSize = null, string? providerName = null, string? containerName = null, int? entityId = null, string? entityType = null)
            : base(isMain, imageName, imageUrl, description, fileType, fileSize, providerName, containerName, entityId, entityType)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}