using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using PawsomePets.Permissions;
using PawsomePets.DogPets;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using PawsomePets.Shared;

namespace PawsomePets.DogPets
{
    public class DogPetsAppService : DogPetsAppServiceBase, IDogPetsAppService
    {
        //<suite-custom-code-autogenerated>
        public DogPetsAppService(IDogPetRepository dogPetRepository, DogPetManager dogPetManager, IDistributedCache<DogPetDownloadTokenCacheItem, string> downloadTokenCache)
            : base(dogPetRepository, dogPetManager, downloadTokenCache)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}